name: Waka Readme

on:
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: windows-latest
    steps:
      - uses: mrCoder23/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
